#!/usr/bin/env bash
#
# demo/policy-gate/run.sh — crown-jewel attack/defense demo (plan.md scenario #4).
#
# Generates a deliberately-insecure Terraform config (SSH open to the world + a
# public S3 bucket) AND a compliant one, plans each, runs the real OPA/conftest
# policy gate (scripts/policy-report.sh), and captures the results as committed
# evidence under docs/demo/policy-gate/.
#
# The configs use a MOCK AWS provider (skip_* flags + fake keys), so the demo is
# plan-only and never touches a real AWS account: `terraform init` needs network
# (provider download) but NO AWS credentials. The insecure HCL is generated at
# runtime in a temp dir and never committed (so it can't trip CI scanners).
#
#   bash demo/policy-gate/run.sh                        # full demo (terraform + conftest)
#   bash demo/policy-gate/run.sh --generate-only <dir>  # just write the .tf for inspection
set -uo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
EVID_DIR="$REPO_ROOT/docs/demo/policy-gate"

write_provider() {
	cat >"$1" <<'TF'
terraform {
  required_version = ">= 1.9"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Mock provider: plan-only demo, never touches a real AWS account (no credentials).
provider "aws" {
  region                      = "ca-central-1"
  access_key                  = "mock"
  secret_key                  = "mock"
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  skip_metadata_api_check     = true
}
TF
}

write_bad() {
	local d="$1"
	mkdir -p "$d"
	write_provider "$d/provider.tf"
	cat >"$d/main.tf" <<'TF'
# DEMO ONLY — intentionally insecure. Generated by demo/policy-gate/run.sh.
# Never committed, never applied; the policy gate blocks it at plan time.

# VIOLATION 1 — SSH open to the entire internet (scenario #4 "crown jewel")
resource "aws_security_group" "bad" {
  name        = "loonvault-demo-bad"
  description = "DEMO ONLY - intentionally insecure"
  vpc_id      = "vpc-demo"
}

resource "aws_security_group_rule" "ssh_world" {
  type              = "ingress"
  from_port         = 22
  to_port           = 22
  protocol          = "tcp"
  cidr_blocks       = ["0.0.0.0/0"]
  security_group_id = aws_security_group.bad.id
}

# VIOLATION 2 — S3 bucket with NO Block Public Access
resource "aws_s3_bucket" "leak" {
  bucket = "loonvault-demo-public-leak"
}

# VIOLATION 3 — public bucket policy (Principal "*", no condition)
resource "aws_s3_bucket_policy" "leak" {
  bucket = aws_s3_bucket.leak.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "PublicRead"
      Effect    = "Allow"
      Principal = "*"
      Action    = "s3:GetObject"
      Resource  = "arn:aws:s3:::loonvault-demo-public-leak/*"
    }]
  })
}
TF
}

write_good() {
	local d="$1"
	mkdir -p "$d"
	write_provider "$d/provider.tf"
	cat >"$d/main.tf" <<'TF'
# DEMO — compliant counterpart. Generated by demo/policy-gate/run.sh.

resource "aws_security_group" "app" {
  name        = "loonvault-demo-app"
  description = "DEMO - app SG"
  vpc_id      = "vpc-demo"
}

resource "aws_security_group" "db" {
  name        = "loonvault-demo-db"
  description = "DEMO - db SG"
  vpc_id      = "vpc-demo"
}

# Compliant: DB ingress is security-group-to-security-group (no CIDR)
resource "aws_security_group_rule" "db_from_app" {
  type                     = "ingress"
  from_port                = 5432
  to_port                  = 5432
  protocol                 = "tcp"
  source_security_group_id = aws_security_group.app.id
  security_group_id        = aws_security_group.db.id
}

# Compliant: private bucket WITH Block Public Access
resource "aws_s3_bucket" "ok" {
  bucket = "loonvault-demo-private"
}

resource "aws_s3_bucket_public_access_block" "ok" {
  bucket                  = aws_s3_bucket.ok.id
  block_public_acls       = true
  ignore_public_acls      = true
  block_public_policy     = true
  restrict_public_buckets = true
}
TF
}

if [ "${1:-}" = "--generate-only" ]; then
	dir="${2:?usage: $0 --generate-only <dir>}"
	write_bad "$dir/bad"
	write_good "$dir/good"
	echo "Generated demo configs under $dir/{bad,good}"
	exit 0
fi

command -v terraform >/dev/null || {
	echo "ERROR: terraform not found" >&2
	exit 1
}
command -v conftest >/dev/null || {
	echo "ERROR: conftest not found — see policies/README.md" >&2
	exit 1
}

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
export TF_PLUGIN_CACHE_DIR="$WORK/.plugin-cache"
mkdir -p "$TF_PLUGIN_CACHE_DIR" "$EVID_DIR"

run_case() {
	local name="$1" dir="$2"
	echo "=================================================================="
	echo ">> DEMO CASE: $name"
	echo "=================================================================="
	(
		cd "$dir" &&
			terraform init -input=false >/dev/null &&
			terraform plan -input=false -out=tfplan.bin >/dev/null &&
			terraform show -json tfplan.bin >plan.json
	) || {
		echo "ERROR: terraform plan failed for the $name case" >&2
		return 1
	}

	# Run the REAL policy gate; capture its output as evidence.
	"$REPO_ROOT/scripts/policy-report.sh" "demo-$name" "$dir/plan.json" 2>&1 |
		tee "$EVID_DIR/${name}-gate-output.txt"
	local rc=${PIPESTATUS[0]}

	# Copy the per-run JSON artifact next to it as committed evidence.
	local art
	art="$(ls -t "$REPO_ROOT"/policy-reports/demo-"$name"-*.json 2>/dev/null | head -1)"
	[ -n "$art" ] && cp "$art" "$EVID_DIR/${name}-report.json"
	echo "($name case gate exit: $rc)"
	echo
}

write_bad "$WORK/bad"
write_good "$WORK/good"
run_case bad "$WORK/bad"
run_case good "$WORK/good"

echo "=================================================================="
echo "Evidence written to docs/demo/policy-gate/ :"
ls -1 "$EVID_DIR" | sed 's/^/  /'
echo
echo "Expected: BAD is DENIED (3 violations), GOOD PASSES."
echo "Commit the evidence files to record scenario #4 (attack blocked)."
