#!/usr/bin/env bash
#
# gen-compliance-matrix.sh
# ---------------------------------------------------------------------------
# Generate the OSFI B-13 / GC Cloud Guardrail compliance-coverage matrix FROM
# the OPA policy `# METADATA` annotations. The matrix is *generated*, never
# hand-maintained — this is the compliance-as-code evidence artifact (the
# pre-deploy / plan-time layer; Prowler covers post-deploy).
#
# Usage:
#   scripts/gen-compliance-matrix.sh            # write policies/COMPLIANCE.md
#   scripts/gen-compliance-matrix.sh --check    # fail if the committed file is stale
#   scripts/gen-compliance-matrix.sh --json     # print machine-readable JSON to stdout
#
# Requires: opa, jq.
# ---------------------------------------------------------------------------
set -euo pipefail

POLICY_DIR="${POLICY_DIR:-policies}"
OUT="${OUT:-policies/COMPLIANCE.md}"

command -v opa >/dev/null 2>&1 || {
	echo "ERROR: 'opa' not found on PATH (needed to read policy annotations)." >&2
	exit 1
}
command -v jq >/dev/null 2>&1 || {
	echo "ERROR: 'jq' not found on PATH." >&2
	exit 1
}

# Extract every control-bearing annotation as one JSON object per policy.
controls_json() {
	opa inspect -a -f json "$POLICY_DIR" | jq -S '
		[ .annotations[]
		  | select(.annotations.custom.controls)
		  | {
		      policy:    ([.path[] | select(.type=="string") | .value] | join(".")),
		      title:     (.annotations.title // "-"),
		      pattern:   (.annotations.custom.pattern // "-"),
		      severity:  (.annotations.custom.severity // "-"),
		      osfi_b13:  (.annotations.custom.controls.osfi_b13 // "-"),
		      guardrail: (.annotations.custom.controls.gc_guardrail // "-"),
		      source:    .location.file
		    }
		] | sort_by(.pattern, .policy)
	'
}

render_markdown() {
	cat <<'HEADER'
# Compliance coverage: OSFI B-13 / GC Cloud Guardrails

> **Generated by `scripts/gen-compliance-matrix.sh` from policy `# METADATA`. Do not edit by hand.**
> Run `just compliance-report` to regenerate. Each row is an enforced OPA policy mapped to the
> control it satisfies at the **pre-deploy / plan-time** layer (Prowler covers post-deploy).

| Pattern | Policy | OSFI B-13 principle | GC Guardrail | Severity | Source |
|---|---|---|---|---|---|
HEADER
	controls_json | jq -r '.[] | "| \(.pattern) | `\(.policy)` | \(.osfi_b13) | \(.guardrail) | \(.severity) | `\(.source)` |"'
}

case "${1:-}" in
--json)
	controls_json
	;;
--check)
	tmp="$(mktemp)"
	render_markdown >"$tmp"
	if diff -q "$OUT" "$tmp" >/dev/null 2>&1; then
		echo "compliance matrix up to date: $OUT"
		rm -f "$tmp"
	else
		echo "DRIFT: $OUT is stale — run 'just compliance-report' and commit." >&2
		diff "$OUT" "$tmp" >&2 || true
		rm -f "$tmp"
		exit 1
	fi
	;;
"")
	render_markdown >"$OUT"
	echo "wrote $OUT"
	;;
*)
	echo "usage: $0 [--check|--json]" >&2
	exit 2
	;;
esac
